version: "3.9"

services:
  seed:
    build: .
    container_name: contacts-seed
    command: ["go", "run", "cmd/main.go", "seed"]
    volumes:
      - contacts-db:/app/db
    depends_on: []
    restart: "no"

  contacts-api:
    build: .
    container_name: contacts-api
    ports:
      - "3000:3000"                          
    environment:
      - GO_ENV=development
    command: ["go", "run", "cmd/main.go"]
    volumes:
      - contacts-db:/app/db
    depends_on:
      seed:
        condition: service_completed_successfully
  
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
  jaeger:
    image: jaegertracing/all-in-one:1.61.0
    ports:
      - "16686:16686"    
      - "14268:14268"   
      - "6831:6831/udp"  
volumes:
  contacts-db:
    driver: local